# Head on waypoints
# waypoints: [[0.0, 0.0], [250.0, 250.0]]

# Crossing from right
# waypoints: [[0.0, 0.0], [0.0, 500.0]]

# Multiple obstacles scenario
waypoints: [[-220.0, 250.0], [250.0, 250.0]]